minimumReleaseAge: 1440
# trustPolicy: no-downgrade

minimumReleaseAgeExclude:
  - '@medusajs/*'

packages:
  - packages/**
  - apps/**
  - libs/**
  - '!apps/demo/**'
  - '!apps/e2e/**'
  - '!apps/typesense-demo/**'

ignoredBuiltDependencies:
  - '@medusajs/telemetry'
  - core-js
  - esbuild
  - msgpackr-extract
  - protobufjs
  - puppeteer
  - sharp

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - nx
