import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '../tokens/index.css'
import { N1Footer } from '@/components/n1-footer'
import { N1Header } from '@/components/n1-header'

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
        <N1Header />
        {children}
        <N1Footer />
      </body>
    </html>
  )
}
