import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '../tokens/index.css'
import { N1Header } from '@/components/header/n1-header'
import { N1Footer } from '@/components/n1-footer'
import { Providers } from '@/components/provider'
import type { ReactNode } from 'react'

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
        <Providers>
          <div className="grid min-h-dvh grid-rows-[auto_1fr_auto]">
            <N1Header />
            {children}
            <N1Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
