import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "../tokens/index.css"
import "./global.css"
import { GoogleTag } from "@techsio/analytics/google"
import { LeadhubPixel } from "@techsio/analytics/leadhub"
import { MetaPixel } from "@techsio/analytics/meta"
import { type ReactNode, Suspense } from "react"
import { PageviewTracker } from "@/components/analytics/pageview-tracker"
import { N1Header } from "@/components/header/n1-header"
import { HeaderProvider } from "@/components/header/store/header-context"
import { N1Footer } from "@/components/n1-footer"
import { Providers } from "@/components/provider"
import { AnalyticsProvider } from "@/providers/analytics-provider"

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="cs">
      <body className={`${openSans.variable} antialiased`}>
        <MetaPixel
          debug
          pixelId={process.env.NEXT_PUBLIC_META_PIXEL_ID ?? ""}
        />
        <GoogleTag adsId={process.env.NEXT_PUBLIC_GOOGLE_ADS_ID ?? ""} debug />
        <LeadhubPixel
          debug
          trackingId={process.env.NEXT_PUBLIC_LEADHUB_TRACKING_ID ?? ""}
        />
        <Providers>
          <AnalyticsProvider>
            <Suspense fallback={null}>
              <PageviewTracker />
            </Suspense>
            <div className="grid min-h-dvh grid-rows-[auto_1fr_auto]">
              <HeaderProvider>
                <N1Header />
              </HeaderProvider>
              {children}
              <N1Footer />
            </div>
          </AnalyticsProvider>
        </Providers>
      </body>
    </html>
  )
}
