FROM node:22-bookworm

ARG PLAYWRIGHT_VERSION=1.56.1

WORKDIR /app

RUN npm init -y
RUN npm i -D @playwright/test@${PLAYWRIGHT_VERSION}
RUN npx -y playwright@${PLAYWRIGHT_VERSION} install --with-deps chromium

ENTRYPOINT ["npx", "playwright"]
